### ISSUE TITLE
Card object not utterable

### ISSUE THREAD

**Issue by psqnt** [pasquantonio/blackjack_terminal#1]
``` Python
Traceback (most recent call last):
  File "blackjack.py", line 468, in <module>
    win_lose(dealer, players, busted)
  File "blackjack.py", line 291, in win_lose
    if check_hand_bust(player.hand[i]):
  File "blackjack.py", line 140, in check_hand_bust
    for card in hand:
TypeError: 'Card' object is not iterable
```

When a player splits, player.hand goes from being an array of cards to an array of hands. I think for some reason a non split hand is being passed to this function on line 291

**Comment by psqnt** [comment]
``` Python
#reset cards
def reset_hand(self):
    self.hand = []
    self.insurance = False
    self.surrender = False
    self.split = False
    self.split_score = []
    self.score = 0
    self.bet = 0
```

I think resetting the split variables inside reset_cards() function fixed it because the error was occurring on non split hands after a round where I had split hands.
